trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"

steps:
  - script: dotnet build --configuraion $(buildConfiguration)
    displayName: "dotnet build $(buildConfiguration)"
